### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by strickland** [zarillion/handynotes-plugins#84]
Sorry forgot to add title, please how do I disable transmog, I don't care for weapons/gear, I just want toy/pet/mounts which are unknown to be shown.

thanks.

EDIT: For BfA maps is what I am requesting, thanks.

**Comment by Krovikan** [comment]
In the world map you have a chest in the right up corner.

Click and you have an option to uncheck the visibility of transmogs.

**Comment by strickland** [comment]
thanks for the quick response, I literally did not know this chest existed in the world map, that is great, however I went there and now I feel stupid because I can't find the transmog? I am there, check picture

https://imgur.com/a/UxV8euJ

**Comment by Krovikan** [comment]
Here (in Shadowlands v27):

https://i.imgur.com/aF6R2w1.png

I think that is in ToDo your request for BfA.

**Comment by strickland** [comment]
That weird, yours is different than mine, I think I got the latest update, don't i? 

how do u have it?

**Comment by Krovikan** [comment]
You are in BfA. And I am in Shadowlands.

The BfA v3 plugin don't have yet this feature.

And mine Shadowlands v27 have the feature (only for Shadowlands maps).

BfA maps needs an update of the version (current is v3) when it have implemented the feature. But for now, is not implemented.

I think is in ToDo of the Author.

**Comment by strickland** [comment]
oh Got you, ok then, thats why I requested this feature, for BfA maps, I hope I can edit the title....I hope he does implement this, still trying to hunt down some of the 8.3 and 8.2 maps which has mounts, toys and pets, but darn everything is showing up because of transmog which I dont care about

**Comment by zarillion** [comment]
I have just released `v4` of the BfA plugin which includes all the Shadowlands features @Krovikan mentioned above.

**Comment by strickland** [comment]
I don't know how to re-open this, but I got v4 @zarillion and still I cannot remove rares from the map or even see the option to remove rare which has transmog, as I said I'm only interested for pets/toys/mounts, and the mod still show all rares.

even known mount still showing

https://imgur.com/a/uxGMV2J

**Comment by zarillion** [comment]
You unchecked "transmog" under the "Show reward types" submenu? I see that submenu in your screenshot so it does look like you have the updates.

**Comment by strickland** [comment]
yes thanks for the response, I just noted I must uncheck show transmog rewards in the main option window, however if you see the other screenshot where the mount Alpaca already known, the icon still is showing, how do I make it so that if a mount is learned then icon shouldnt be shown?
